# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Jiancai Liao
tagline:          'Jiancai Liao'
description:      'Marketing PhD candidate at Aalto University. I research consumer welling, health marketing, healthcare policy, with a cross-disciplinary approach.'
url:              https://jiancailiao.github.io/
baseurl:          #'/blog'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:          Jiancai Liao
name:           'Jiancai Liao'
email:          jiancai.liao@aalto.fi


paginate:         5
paginate_path:    #'/page:num'
                    # Or '/blog/page:num' if you want to move your index pages
google_analytics:   UA-150989928-1

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  false
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
